updated ci workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,7 @@ jobs:
 
       - name: Run Maven Tests
         id: run_tests
-        run: mvn clean test || true
+        run: mvn clean test || true  # Prevents workflow from stopping if tests fail
 
       - name: Extract Failed Test Names
         if: always()
@@ -41,7 +41,7 @@ jobs:
         with:
           name: reports
           path: |
-            reports/**
+            test-output/**
             screenshots/**
 
       - name: Slack Notification
